server:
  port: 9092
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9871/eureka/