##  服务端口
server:
  port: 2020
spring:
  datasource:
      #加密方式：encrypt 表示使用统一加密的方式，加密串为encrypt_label
      encrypt_type: default
      encrypt_label: default
      url: jdbc:mysql://172.21.1.13:3306/settle?useUnicode=true&characterEncoding=utf-8
      username: chnpt1
      password: chnpt123
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat
  jpa:
    properties:
      hibernate:
        current_session_context_class:  org.springframework.orm.hibernate4.SpringSessionContext

  redis:
    host: 172.21.10.38
    port: 6379
#  zipkin:
#    base-url: http://10.10.8.2:9050
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url:  http://localhost:2020/swagger-ui.html
  client:
      service-url:
        defaultZone: http://localhost:2018/eureka/
###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####

###如下Oauth2.0配置参考##
###https://stackoverflow.com/questions/30327269/spring-oauth-authorization-server-behind-spring-cloud-zuul-proxy##
###https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc##
###http://wiselyman.iteye.com/blog/2379419##
#######
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    uaa:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: iEase-auth-server
    demo:
      path: /demo/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: iEase-demo-server
    iease:
      path: /iease/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: iEase-settle-rule-server
    settle:
      path: /settle/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: iEase-settle-platform
    base:
      path: /base/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: iEase-base-server


security:
  basic:
    enabled: false
feign:
  hystrix:
   enabled: true
#  oauth2:
#    client:
#      access-token-uri: http://iEase-auth-server/oauth/token ##网关的地址
#      user-authorization-uri: http://iEase-auth-server/oauth/authorize
#      client-id: webApp
#      client-secret: webApp
     #通过redis获取认证信息
#    resource:
#      token-info-uri:  http://localhost:2021/oauth/check_token
#      prefer-token-info: true
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
#不需要进行权限验证的url
urls:
  ignore:
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /uaa/*
    - /v2/api-docs